# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(blank=True, max_length=4)),
                ('table_run', models.BooleanField()),
                ('forfeit', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='GameOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='LineupEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('display_name', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSeasonSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(default=0, verbose_name='Wins')),
                ('losses', models.IntegerField(default=0, verbose_name='Losses')),
                ('four_ohs', models.IntegerField(default=0, verbose_name='4-0s')),
                ('table_runs', models.IntegerField(default=0, verbose_name='Table Runs')),
                ('win_percentage', models.FloatField(default=0.0, verbose_name='Win Percentage')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_name', models.CharField(max_length=16)),
                ('away_name', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official', models.BooleanField(default=False)),
                ('games', models.ManyToManyField(blank=True, to='stats.Game')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Match')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date of first week')),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.GameOrder')),
                ('play_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.PlayPosition')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('away_wins', models.IntegerField(default=0, verbose_name='Away Wins')),
                ('away_losses', models.IntegerField(default=0, verbose_name='Away Losses')),
                ('home_wins', models.IntegerField(default=0, verbose_name='Home Wins')),
                ('home_losses', models.IntegerField(default=0, verbose_name='Home Losses')),
                ('win_percentage', models.FloatField(default=0.0, verbose_name='Win Percentage')),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Division')),
                ('players', models.ManyToManyField(blank=True, to='stats.Player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Season')),
                ('sponsor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Sponsor')),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=32, null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Season')),
            ],
        ),
        migrations.AddField(
            model_name='playerseasonsummary',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Season'),
        ),
        migrations.AddField(
            model_name='match',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Season'),
        ),
        migrations.AddField(
            model_name='match',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Week'),
        ),
        migrations.AddField(
            model_name='lineupentry',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Player'),
        ),
        migrations.AddField(
            model_name='lineupentry',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.PlayPosition'),
        ),
        migrations.AddField(
            model_name='game',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.GameOrder'),
        ),
        migrations.AddField(
            model_name='division',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Season'),
        ),
        migrations.CreateModel(
            name='AwayLineupEntry',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('stats.lineupentry',),
        ),
        migrations.CreateModel(
            name='AwayPlayer',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('stats.player',),
        ),
        migrations.CreateModel(
            name='AwayPlayPosition',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('stats.playposition',),
        ),
        migrations.CreateModel(
            name='AwaySubstitution',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('stats.substitution',),
        ),
        migrations.CreateModel(
            name='AwayTeam',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('stats.team',),
        ),
        migrations.CreateModel(
            name='HomeLineupEntry',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('stats.lineupentry',),
        ),
        migrations.CreateModel(
            name='HomePlayer',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('stats.player',),
        ),
        migrations.CreateModel(
            name='HomePlayPosition',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('stats.playposition',),
        ),
        migrations.CreateModel(
            name='HomeSubstitution',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('stats.substitution',),
        ),
        migrations.CreateModel(
            name='HomeTeam',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('stats.team',),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='away_lineup',
            field=models.ManyToManyField(blank=True, to='stats.AwayLineupEntry'),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='away_substitutions',
            field=models.ManyToManyField(to='stats.AwaySubstitution'),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='home_lineup',
            field=models.ManyToManyField(blank=True, to='stats.HomeLineupEntry'),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='home_substitutions',
            field=models.ManyToManyField(to='stats.HomeSubstitution'),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.AwayTeam'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.HomeTeam'),
        ),
        migrations.AddField(
            model_name='gameorder',
            name='away_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.AwayPlayPosition'),
        ),
        migrations.AddField(
            model_name='gameorder',
            name='home_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.HomePlayPosition'),
        ),
        migrations.AddField(
            model_name='game',
            name='away_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.AwayPlayer'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.HomePlayer'),
        ),
    ]
