# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
