# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_team_sponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('display_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='votes',
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(to='stats.Player'),
        ),
    ]
