# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoresheet',
            name='creator_session',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
