# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-01 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_scoresheet_creator_session'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerseasonsummary',
            options={'ordering': ['-win_percentage']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-win_percentage']},
        ),
        migrations.AddField(
            model_name='gameorder',
            name='home_breaks',
            field=models.BooleanField(default=True),
        ),
    ]
