# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20160401_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoresheet',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
