# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 04:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_scoresheet_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoresheet',
            name='complete',
        ),
    ]
