# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_remove_scoresheet_complete'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AwayLineupEntry',
        ),
        migrations.DeleteModel(
            name='HomeLineupEntry',
        ),
        migrations.RemoveField(
            model_name='lineupentry',
            name='position',
        ),
        migrations.CreateModel(
            name='AwayLineupEntry',
            fields=[
                ('lineupentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stats.LineupEntry')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.AwayPlayPosition')),
            ],
            bases=('stats.lineupentry',),
        ),
        migrations.CreateModel(
            name='HomeLineupEntry',
            fields=[
                ('lineupentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stats.LineupEntry')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.HomePlayPosition')),
            ],
            bases=('stats.lineupentry',),
        ),
    ]
