# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-17 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_auto_20160402_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoresheet',
            name='comment',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
