# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_auto_20160417_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoresheet',
            name='comment',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
