# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-30 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_auto_20160418_0538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-ranking']},
        ),
        migrations.AddField(
            model_name='team',
            name='ranking',
            field=models.IntegerField(null=True),
        ),
    ]
