# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-30 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0010_auto_20160430_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerseasonsummary',
            name='ranking',
            field=models.IntegerField(null=True),
        ),
    ]
