# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-30 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0011_playerseasonsummary_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='minimum_games',
            field=models.IntegerField(null=True),
        ),
    ]
