# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-18 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0012_season_minimum_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='rank_tie_breaker',
            field=models.IntegerField(null=True),
        ),
    ]
