# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-19 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0013_team_rank_tie_breaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameorder',
            name='tiebreaker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='playoff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='forfeit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='table_run',
            field=models.BooleanField(default=False),
        ),
    ]
