# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-19 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0014_auto_20160519_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='playposition',
            name='tiebreaker',
            field=models.BooleanField(default=False),
        ),
    ]
