# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-06 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0018_auto_20160605_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineupentry',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Player'),
        ),
    ]
