# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-11 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0019_auto_20160606_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Season'),
        ),
        migrations.AlterField(
            model_name='team',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Season'),
        ),
        migrations.AlterField(
            model_name='week',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Season'),
        ),
    ]
