# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-03 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0020_auto_20160811_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='away_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_player', to='stats.AwayPlayer'),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_player', to='stats.HomePlayer'),
        ),
        migrations.AlterField(
            model_name='gameorder',
            name='away_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_position', to='stats.AwayPlayPosition'),
        ),
        migrations.AlterField(
            model_name='gameorder',
            name='home_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_position', to='stats.HomePlayPosition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='stats.AwayTeam'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='stats.HomeTeam'),
        ),
        migrations.AlterField(
            model_name='scoresheet',
            name='away_lineup',
            field=models.ManyToManyField(blank=True, related_name='away_lineup', to='stats.AwayLineupEntry'),
        ),
        migrations.AlterField(
            model_name='scoresheet',
            name='away_substitutions',
            field=models.ManyToManyField(related_name='away_substitution', to='stats.AwaySubstitution'),
        ),
        migrations.AlterField(
            model_name='scoresheet',
            name='home_lineup',
            field=models.ManyToManyField(blank=True, related_name='home_lineup', to='stats.HomeLineupEntry'),
        ),
        migrations.AlterField(
            model_name='scoresheet',
            name='home_substitutions',
            field=models.ManyToManyField(related_name='home_substitution', to='stats.HomeSubstitution'),
        ),
    ]
