# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-25 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0021_auto_20160903_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substitution',
            name='play_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.PlayPosition'),
        ),
    ]
