# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-11 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0022_auto_20161125_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerseasonsummary',
            name='win_percentage',
            field=models.FloatField(default=0.0, null=True, verbose_name='Win Percentage'),
        ),
    ]
