# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0023_auto_20170811_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameorder',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
