# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 04:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0024_gameorder_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameorder',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='gameorder',
            name='name',
        ),
    ]
