# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0025_auto_20170819_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerseasonsummary',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Team'),
        ),
    ]
