# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0025_auto_20170819_0454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('date', models.DateField()),
                ('play_format', models.IntegerField(choices=[(0, 'Single Elimination'), (1, 'Double Elimination')])),
                ('race_to', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TournamentMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_order', models.IntegerField()),
                ('bye', models.BooleanField(default=False)),
                ('player_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_a', to='stats.Player')),
                ('player_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_b', to='stats.Player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Tournament')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentPlayPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Player')),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='play_positions',
            field=models.ManyToManyField(to='stats.TournamentPlayPosition'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(blank=True, to='stats.Player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Season'),
        ),
    ]
