# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0026_auto_20171021_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='tables',
        ),
        migrations.AddField(
            model_name='table',
            name='sponsor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Sponsor'),
        ),
    ]
