# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-17 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0026_playerseasonsummary_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerseasonsummary',
            name='team',
        ),
    ]
