# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0026_auto_20170824_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='play_positions',
            field=models.ManyToManyField(blank=True, to='stats.TournamentPlayPosition'),
        ),
    ]
