# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0027_auto_20170824_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='tournament',
        ),
        migrations.AddField(
            model_name='tournament',
            name='matches',
            field=models.ManyToManyField(to='stats.TournamentMatch'),
        ),
    ]
