# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 04:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0028_auto_20170826_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_winning_player', to='stats.Player'),
        ),
    ]
