# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-18 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0028_auto_20180219_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Season'),
        ),
    ]
