# Generated by Django 2.0.3 on 2018-04-16 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0029_auto_20180318_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekDivisionMatchup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('away_division', models.ForeignKey(limit_choices_to=models.Q(season__is_default=True), on_delete=django.db.models.deletion.CASCADE, related_name='away_division', to='stats.Division')),
                ('home_division', models.ForeignKey(limit_choices_to=models.Q(season__is_default=True), on_delete=django.db.models.deletion.CASCADE, related_name='home_division', to='stats.Division')),
                ('week', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Week')),
            ],
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(season__is_default=True), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='stats.AwayTeam'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(season__is_default=True), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='stats.HomeTeam'),
        ),
        migrations.AlterField(
            model_name='match',
            name='week',
            field=models.ForeignKey(limit_choices_to=models.Q(season__is_default=True), on_delete=django.db.models.deletion.CASCADE, to='stats.Week'),
        ),
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.ForeignKey(limit_choices_to=models.Q(season__is_default=True), null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Division'),
        ),
    ]
