# Generated by Django 2.0.3 on 2018-04-19 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0030_auto_20180326_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoresheet',
            name='official',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Official'), (2, 'Needs Changes')], default=0, verbose_name='Status'),
        ),
    ]
