# Generated by Django 2.0.3 on 2018-04-16 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0030_week_division_matchups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekdivisionmatchup',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foo', to='stats.Week'),
        ),
    ]
