# Generated by Django 2.0.3 on 2018-04-19 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0030_auto_20180406_0411'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekDivisionMatchup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('away_division', models.ForeignKey(limit_choices_to=models.Q(season__is_default=True), on_delete=django.db.models.deletion.CASCADE, related_name='away_division', to='stats.Division')),
                ('home_division', models.ForeignKey(limit_choices_to=models.Q(season__is_default=True), on_delete=django.db.models.deletion.CASCADE, related_name='home_division', to='stats.Division')),
                ('week', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Week')),
            ],
        ),
    ]
