# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0030_auto_20170826_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentmatch',
            name='player_a_match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_a_source_match', to='stats.TournamentMatch'),
        ),
        migrations.AlterField(
            model_name='tournamentmatch',
            name='player_b_match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_b_source_match', to='stats.TournamentMatch'),
        ),
    ]
