# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 04:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0031_auto_20170826_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentMatchPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot', models.CharField(max_length=1)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Player')),
            ],
        ),
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='player_a',
        ),
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='player_a_match',
        ),
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='player_b',
        ),
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='player_b_match',
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='source_matches',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.TournamentMatch'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='matches',
            field=models.ManyToManyField(blank=True, to='stats.TournamentMatch'),
        ),
        migrations.AlterField(
            model_name='tournamentmatch',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_winning_player', to='stats.TournamentMatchPlayer'),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='players',
            field=models.ManyToManyField(to='stats.TournamentMatchPlayer'),
        ),
    ]
