# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0032_auto_20170829_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentmatchplayer',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Player'),
        ),
    ]
