# Generated by Django 2.0.3 on 2018-04-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0032_auto_20180421_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='rank_tie_breaker',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
