# Generated by Django 2.0.3 on 2018-05-12 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0033_rank_tie_breaker_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Sponsor')),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='sponsor',
        ),
        migrations.AddField(
            model_name='match',
            name='alternate_table',
            field=models.ForeignKey(default=None, blank=True, null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='stats.Table'),
        ),
        migrations.AddField(
            model_name='team',
            name='table',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Table'
            ),
        ),
    ]
