# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0033_auto_20170831_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='source_matches',
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='source_matches',
            field=models.ManyToManyField(related_name='_tournamentmatch_source_matches_+', to='stats.TournamentMatch'),
        ),
    ]
