# Generated by Django 2.0.3 on 2018-05-27 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0034_venue_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=64)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Season')),
                ('teams', models.ManyToManyField(to='stats.Team')),
            ],
        ),
        migrations.CreateModel(
            name='TieBreakerResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divisional', models.BooleanField(default=False)),
                ('rank_change', models.IntegerField()),
                ('attribute', models.CharField(max_length=64)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Team')),
                ('tie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Tie')),
            ],
        ),
    ]
