# Generated by Django 2.1.7 on 2019-03-25 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0037_team_captain'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerseasonsummary',
            name='trueskill_mu',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonsummary',
            name='trueskill_sigma',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
