# Generated by Django 2.1.7 on 2019-04-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0037_team_captain'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerseasonsummary',
            name='elo',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='playerseasonsummary',
            name='last_rated_game',
            field=models.IntegerField(null=True),
        ),
    ]
