# Generated by Django 2.0.3 on 2018-07-02 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0037_team_captain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bracket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('w', 'winners'), ('l', 'losers')])),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Bracket')),
            ],
        ),
        migrations.CreateModel(
            name='TeamPlayoffMatchup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('a_want_winner', models.BooleanField()),
                ('b_want_winner', models.BooleanField()),
                ('play_order', models.IntegerField()),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Round')),
                ('source_match_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='match_a', to='stats.TeamPlayoffMatchup')),
                ('source_match_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='match_b', to='stats.TeamPlayoffMatchup')),
                ('team_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_a', to='stats.Team')),
                ('team_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_b', to='stats.Team')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.TextField(choices=[('team_playoff', 'Team Playoff'), ('scotch_doubles', 'Scotch Doubles')])),
                ('elimination', models.TextField(choices=[('single', 'Single Elimination'), ('double', 'Double Elimination')])),
            ],
        ),
        migrations.AddField(
            model_name='bracket',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Tournament'),
        ),
    ]
