# Generated by Django 2.1.7 on 2019-04-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0038_elo'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='away_elo',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='home_elo',
            field=models.FloatField(null=True),
        ),
    ]
