# Generated by Django 2.0.3 on 2018-07-07 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0038_auto_20180707_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='tournament',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stats.Tournament'),
            preserve_default=False,
        ),
    ]
