# Generated by Django 2.1.7 on 2019-05-21 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0039_game_elo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(default=1, limit_choices_to=models.Q(season__is_default=True), on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='stats.AwayTeam'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(default=1, limit_choices_to=models.Q(season__is_default=True), on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='stats.HomeTeam'),
            preserve_default=False,
        ),
    ]
