# Generated by Django 2.0.3 on 2018-07-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0039_participant_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentmatchup',
            name='a_want_winner',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='tournamentmatchup',
            name='b_want_winner',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='tournamentmatchup',
            name='play_order',
            field=models.IntegerField(null=True),
        ),
    ]
