# Generated by Django 2.1.11 on 2019-12-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0042_elo_refactor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['venue', '-name']},
        ),
        migrations.AddField(
            model_name='table',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
