# Generated by Django 2.1.11 on 2019-09-12 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0042_elo_refactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bracket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('w', 'Winners'), ('l', 'Losers')])),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('team', 'Team'), ('player', 'Player')])),
                ('player', models.ManyToManyField(blank=True, to='stats.Player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Bracket')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.TextField(choices=[('team_playoff', 'Team Playoff'), ('scotch_doubles', 'Scotch Doubles')])),
                ('elimination', models.TextField(choices=[('single', 'Single Elimination'), ('double', 'Double Elimination')])),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Season')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentMatchup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('a_want_winner', models.NullBooleanField()),
                ('b_want_winner', models.NullBooleanField()),
                ('play_order', models.IntegerField(null=True)),
                ('participant_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='participant_a', to='stats.Participant')),
                ('participant_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='participant_b', to='stats.Participant')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Round')),
                ('source_match_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='match_a', to='stats.TournamentMatchup')),
                ('source_match_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='match_b', to='stats.TournamentMatchup')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Participant')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Tournament'),
        ),
        migrations.AddField(
            model_name='bracket',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Tournament'),
        ),
    ]
