# Generated by Django 2.1.11 on 2019-12-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0043_inactive_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='registration_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='registration_start',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='creator_session',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='pub_date',
            field=models.DateField(verbose_name='date of first week'),
        ),
    ]
