# Generated by Django 2.1.11 on 2019-11-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0043_tournaments'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatchup',
            name='is_necessary',
            field=models.BooleanField(default=True),
        ),
    ]
