# Generated by Django 2.1.11 on 2019-11-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0044_matchup_is_necessary'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='flopped',
            field=models.BooleanField(default=False),
        ),
    ]
