# Generated by Django 2.1.11 on 2019-12-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0044_team_registration_access_controls'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={'ordering': ['sort_name']},
        ),
        migrations.AddField(
            model_name='sponsor',
            name='sort_name',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
