# Generated by Django 2.1.15 on 2019-12-27 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0043_tournaments'),
        ('stats', '0045_sponsor_sort_name'),
    ]

    operations = [
    ]
