# Generated by Django 3.2.5 on 2021-12-05 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0046_merge_20191227_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mu', models.FloatField(default=1000)),
                ('sigma', models.FloatField(default=333)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerRatingBookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.game')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='playerseasonsummary',
            name='elo',
        ),
        migrations.AlterField(
            model_name='tournamentmatchup',
            name='a_want_winner',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='tournamentmatchup',
            name='b_want_winner',
            field=models.BooleanField(null=True),
        ),
        migrations.DeleteModel(
            name='PlayerElo',
        ),
    ]
