# Generated by Django 3.2.5 on 2022-05-12 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0047_add_trueskill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='away_losses',
        ),
        migrations.RemoveField(
            model_name='team',
            name='away_wins',
        ),
        migrations.RemoveField(
            model_name='team',
            name='home_losses',
        ),
        migrations.RemoveField(
            model_name='team',
            name='home_wins',
        ),
        migrations.AddField(
            model_name='team',
            name='losses',
            field=models.IntegerField(default=0, verbose_name='Losses'),
        ),
        migrations.AddField(
            model_name='team',
            name='wins',
            field=models.IntegerField(default=0, verbose_name='Wins'),
        ),
        migrations.CreateModel(
            name='ScoreAdjustment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('description', models.TextField(default=None, max_length=1024, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.team')),
            ],
        ),
    ]
